<?php

namespace AulasBundle\Repository;

/**
 * MenuSubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuSubRepository extends \Doctrine\ORM\EntityRepository
{
}
