<?php

namespace AulasBundle\Repository;

/**
 * PerfilDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
