<?php

namespace AulasBundle\Repository;

/**
 * UsuariosPerfilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosPerfilesRepository extends \Doctrine\ORM\EntityRepository
{
}
